#ifndef __RulesListGui__
#define __RulesListGui__

/**
@file
Subclass of RulesList, which is generated by wxFormBuilder.
*/

#include "RulesList.h"

//// end generated include

/** Implementing RulesList */
class RulesListGui : public RulesList
{
	protected:
		// Handlers for RulesList events.
		void OnStartService( wxCommandEvent& event );
		void OnRuleUp( wxCommandEvent& event );
		void OnRuleDown( wxCommandEvent& event );
		void OnAddRules( wxCommandEvent& event );
		void OnModifyRules( wxCommandEvent& event );
		void OnDeleteRules( wxCommandEvent& event );
		void OnSystemSettings( wxCommandEvent& event );
		void OnExit( wxCommandEvent& event );
	public:
		/** Constructor */
		RulesListGui( wxWindow* parent );
	//// end generated class members
	
};

#endif // __RulesListGui__
